### ISSUE TITLE
Request handling roadmap

### ISSUE THREAD

**Issue by NPGaming2971** [sorcerer-worker/rickchurian-cli#1]
- Complete api data structure
+ [x] Character
+ [x] Episode
+ [x] Location 

- Manager to work with api endpoint
+ [x] CharacterManager
+ [x] LocationManager 
+ [x] EpisodeManager

- Other
+ [x] Caching, perhaps?

**Comment by sorcerer-worker** [comment]
100% Slaughtered. Except the caching.
